import { useState } from 'react'
import {
  ChevronDown,
  ChevronUp,
  ExternalLink,
  GitBranch,
  PlayCircle,
  Star,
} from 'lucide-react'
import { projects, type Project } from '../data/portfolio'
import { MotionSection } from './MotionSection'
import { SectionHeading } from './SectionHeading'

function ProjectLink({
  href,
  label,
  disabledLabel,
  ariaLabel,
  variant,
  external = true,
}: {
  href: string
  label: string
  disabledLabel: string
  ariaLabel: string
  variant: 'outline' | 'primary'
  external?: boolean
}) {
  const baseClass =
    'inline-flex min-h-11 items-center justify-center gap-2 rounded-md px-3 py-3 text-sm font-semibold transition focus:outline-none focus:ring-2 focus:ring-cyan-200'
  const variantClass =
    variant === 'primary'
      ? 'bg-cyan-400/12 text-cyan-100 hover:bg-cyan-400/20'
      : 'border border-white/15 text-slate-100 hover:bg-white/10'
  const disabledClass =
    variant === 'primary'
      ? 'cursor-not-allowed bg-slate-800/60 text-slate-500'
      : 'cursor-not-allowed border border-white/10 text-slate-500'

  if (!href) {
    return (
      <span className={`${baseClass} ${disabledClass}`} aria-disabled="true">
        {disabledLabel}
      </span>
    )
  }

  return (
    <a
      href={href}
      aria-label={ariaLabel}
      target={external ? '_blank' : undefined}
      rel={external ? 'noopener noreferrer' : undefined}
      className={`${baseClass} ${variantClass}`}
    >
      {label}
      {variant === 'primary' ? (
        <ExternalLink size={18} aria-hidden="true" />
      ) : (
        <GitBranch size={18} aria-hidden="true" />
      )}
    </a>
  )
}

function demoHref(project: Project) {
  if (project.internalDemoPath) {
    return project.internalDemoPath
  }
  if (project.demoType === 'video') {
    return project.internalDemoPath ?? ''
  }
  if (project.demoType === 'live-app') {
    return project.demoUrl
  }
  return ''
}

function TennisVideoDemo({ project }: { project: Project }) {
  if (!project.videoAsset || !project.posterAsset) {
    return null
  }

  return (
    <section
      id="tennis-video-demo"
      className="mt-8 scroll-mt-24 overflow-hidden rounded-lg border border-cyan-300/25 bg-slate-950/70 shadow-2xl shadow-black/30"
      aria-labelledby="tennis-video-demo-title"
    >
      <div className="grid gap-0 lg:grid-cols-[1.25fr_0.75fr]">
        <div className="bg-black">
          <video
            className="aspect-video h-full w-full bg-black object-contain"
            controls
            playsInline
            preload="metadata"
            poster={project.posterAsset}
          >
            <source src={project.videoAsset} type="video/mp4" />
            Your browser does not support HTML5 video playback.
          </video>
        </div>
        <div className="p-6">
          <div className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs font-semibold text-cyan-100">
            <PlayCircle size={14} aria-hidden="true" />
            Video Demo
          </div>
          <h3 id="tennis-video-demo-title" className="mt-4 text-2xl font-semibold text-white">
            {project.title}
          </h3>
          <p className="mt-4 text-sm leading-7 text-slate-300">
            This result video was generated by rerunning the repository Kalman
            tracker on the included Shanghai 2014 Federer vs Djokovic test clip.
            The original source footage is not presented here as owned material;
            this embedded asset is the derived tracking output for portfolio review.
          </p>
          <dl className="mt-5 grid gap-3 text-sm">
            <div className="rounded-md border border-white/10 bg-white/[0.04] p-3">
              <dt className="text-xs uppercase tracking-[0.14em] text-cyan-300">
                Pipeline
              </dt>
              <dd className="mt-1 text-slate-200">
                Input video, frame decoding, CV detection cues, Kalman smoothing,
                overlay rendering, H.264 web export
              </dd>
            </div>
            <div className="rounded-md border border-white/10 bg-white/[0.04] p-3">
              <dt className="text-xs uppercase tracking-[0.14em] text-cyan-300">
                Source
              </dt>
              <dd className="mt-1 text-slate-200">
                Test clip from the upstream repository, documented as the first
                set from Shanghai 2014 Federer vs Djokovic.
              </dd>
            </div>
          </dl>
          <a
            href={project.repositoryUrl}
            aria-label={`Open ${project.title} GitHub repository`}
            target="_blank"
            rel="noopener noreferrer"
            className="mt-5 inline-flex items-center justify-center gap-2 rounded-md border border-white/15 px-4 py-3 text-sm font-semibold text-slate-100 transition hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-cyan-200"
          >
            GitHub Repository
            <GitBranch size={18} aria-hidden="true" />
          </a>
        </div>
      </div>
    </section>
  )
}

export function FeaturedProjects() {
  const [openProject, setOpenProject] = useState(projects[0]?.title ?? '')
  const videoProject = projects.find((project) => project.demoType === 'video')

  return (
    <MotionSection id="projects" className="border-y border-white/5 bg-white/[0.02]">
      <SectionHeading
        eyebrow="Featured Projects"
        title="Engineering case studies"
        description="Each project card keeps the main story scannable and opens into verified problem, contribution, result, and limitation details."
      />

      <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-4">
        {projects.map((project) => (
          <article
            key={project.title}
            className={`flex min-h-[610px] flex-col overflow-hidden rounded-lg border bg-slate-900/70 shadow-xl shadow-black/20 transition hover:-translate-y-1 ${
              project.featured
                ? 'border-cyan-300/45 shadow-cyan-950/20'
                : 'border-white/10 hover:border-cyan-300/30'
            }`}
          >
            <div className="relative aspect-[16/10] bg-slate-950">
              <img
                src={project.image}
                alt={`${project.title} project visual`}
                className="h-full w-full object-cover opacity-95"
              />
              <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950/95 to-transparent p-4">
                <p className="text-xs text-slate-300">{project.imageStatus}</p>
              </div>
              {project.featured && (
                <div className="absolute left-4 top-4 inline-flex items-center gap-2 rounded-full border border-cyan-200/25 bg-cyan-200/15 px-3 py-1 text-xs font-semibold text-cyan-100">
                  <Star size={13} aria-hidden="true" />
                  Featured
                </div>
              )}
            </div>

            <div className="flex flex-1 flex-col p-5">
              <h3 className="min-h-16 text-xl font-semibold leading-8 text-white">
                {project.title}
              </h3>

              <p className="mt-4 min-h-32 text-sm leading-7 text-slate-300">
                {project.overview}
              </p>

              <div className="mt-5 flex flex-wrap gap-2">
                {project.techStack.slice(0, 6).map((tech) => (
                  <span
                    key={tech}
                    className="rounded-full border border-violet-300/20 bg-violet-400/10 px-3 py-1 text-xs text-violet-100"
                  >
                    {tech}
                  </span>
                ))}
              </div>

              <div className="mt-auto pt-6">
                <div className="grid grid-cols-2 gap-3">
                  <ProjectLink
                    href={project.repositoryUrl}
                    label="GitHub"
                    disabledLabel="Repository unavailable"
                    ariaLabel={`Open ${project.title} GitHub repository`}
                    variant="outline"
                  />
                  <ProjectLink
                    href={demoHref(project)}
                    label={project.demoLabel}
                    disabledLabel="Demo unavailable"
                    ariaLabel={project.accessibleLabel}
                    variant="primary"
                    external={!project.internalDemoPath && project.demoType === 'live-app'}
                  />
                </div>

                {project.contextUrl && project.contextLabel && (
                  <a
                    href={project.contextUrl}
                    aria-label={`Open ${project.contextLabel}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-md border border-cyan-300/20 bg-cyan-300/[0.06] px-3 py-3 text-sm font-semibold text-cyan-100 transition hover:bg-cyan-300/12 focus:outline-none focus:ring-2 focus:ring-cyan-200"
                  >
                    {project.contextLabel}
                    <ExternalLink size={17} aria-hidden="true" />
                  </a>
                )}

                <button
                  type="button"
                  className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-md border border-white/10 bg-white/[0.04] px-4 py-3 text-sm font-semibold text-slate-100 transition hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-cyan-200"
                  aria-expanded={openProject === project.title}
                  onClick={() =>
                    setOpenProject((current) =>
                      current === project.title ? '' : project.title,
                    )
                  }
                  >
                  Case Study
                  {openProject === project.title ? (
                    <ChevronUp size={18} aria-hidden="true" />
                  ) : (
                    <ChevronDown size={18} aria-hidden="true" />
                  )}
                </button>
              </div>

              {openProject === project.title && (
                <div className="mt-4 space-y-4 rounded-lg border border-white/10 bg-slate-950/55 p-4">
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-300">
                      Overview
                    </p>
                    <p className="mt-2 text-sm leading-7 text-slate-300">
                      {project.description}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-300">
                      Problem
                    </p>
                    <p className="mt-2 text-sm leading-7 text-slate-300">
                      {project.problemDefinition}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-300">
                      My Contribution
                    </p>
                    <ul className="mt-2 list-disc space-y-2 pl-5 text-sm leading-7 text-slate-300">
                      {project.myContribution.map((item) => (
                        <li key={item}>{item}</li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-300">
                      Results
                    </p>
                    <ul className="mt-2 list-disc space-y-2 pl-5 text-sm leading-7 text-slate-300">
                      {project.keyResults.map((result) => (
                        <li key={result}>{result}</li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-300">
                      Tools
                    </p>
                    <div className="mt-2 flex flex-wrap gap-2">
                      {project.verifiedTechStack.map((tech) => (
                        <span
                          key={tech}
                          className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs text-cyan-100"
                        >
                          {tech}
                        </span>
                      ))}
                    </div>
                  </div>
                  <div>
                    <p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-300">
                      Link Status
                    </p>
                    <p className="mt-2 text-sm leading-7 text-slate-300">
                      {project.deploymentStatus}
                    </p>
                  </div>
                </div>
              )}
            </div>
          </article>
        ))}
      </div>
      {videoProject && <TennisVideoDemo project={videoProject} />}
    </MotionSection>
  )
}
